# NUMPY

## LISTS
### One-deminsional LIST (one column)

In [1]:
a = [1, 3, 5, 7, 9]
print(a[2:4])
print()

[5, 7]



### Two-deminsional LIST (two columns)

In [2]:
# b = [[1, 3, 5, 7, 9],[2, 4, 6, 8, 10]]
b = [
     [1, 3, 5, 7, 9], #ROW 1
     [2, 4, 6, 8, 10] #ROW 2
    ]

### Print ROW 1

In [3]:
print(b[0])
print()

[1, 3, 5, 7, 9]



### From LIST B print the value found at the intersection of
### ROW 2 (index 1) : COLUMN 3 (index 2)

In [4]:
print(b[1][2])

6


### Math with LISTS (basically does not work)

In [5]:
a = [1, 3, 5, 7, 9]
b = [2, 4, 6, 8, 10]

print("Appending two lists...")
c = a + b  #Append NOT add
print(c)
print()

#Math did not work. 

Appending two lists...
[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]



### How could we do it then?  What is the "work-around"

In [6]:
#LOOPS!!!!
print("Adding to lists together...")
#Here is one option...
#Create an empty LIST
c = []

#Loop through each value in the list
for i in range(len(a)):
    # Append the sum of a & b to the list c
    c.append(a[i] + b[i])

#Did it work?    
print(c)

Adding to lists together...
[3, 7, 11, 15, 19]


## Why <font color="red">NUMPY</font> is better:

### Math with NUMPY

In [4]:
#IMPORT NUMPY since it is not part of base python
import numpy as np

# Make NUMPY arrays out of two LISTS
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4, 6, 8, 10])

# ADD two NUMPY arrays
c = a + b

#Did it work?
print(c)

[ 3  7 11 15 19]


### Creating NUMPY arrays...

In [8]:
print("Zeros...")
print(np.zeros(5))

Zeros...
[0. 0. 0. 0. 0.]


In [5]:
print("Print two rows and 3 columns of Zeros...")
print(np.zeros( (2, 3) ))
# print(np.zeros(2, 3)) is an error

Print two rows and 3 columns of Zeros...
[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print("Print 4 ones...")
print(np.ones(4))

Print 4 ones...
[1. 1. 1. 1.]


In [11]:
print("Print 3 columns and two rows of ones...")
print(np.ones( (3, 2) ))

Print 3 columns and two rows of ones...
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
print("Print 2 rows and 4 columns of .1")
print(np.full( (2, 4), 0.1 ))

Print 2 rows and 4 columns of .1
[[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]


### :-(  Only one datatype for NUMPY at a time

#### LIST

In [13]:
#List multi-datatype? NO problem!
list_a = [1, 's', 0.1]
print("Original values intact...")
print(list_a)

Original values intact...
[1, 's', 0.1]


#### NumPy Array

In [14]:
#NUMPY multi-datatype?  PROBLEM!
print("Oh no. Converted to strings...")
np_list_a = np.array(list_a)
print(np_list_a)

Oh no. Converted to strings...
['1' 's' '0.1']


### NumPy Array Properties (Size)

In [15]:
arr = np.array([[1, 3, 5],
                [2, 4, 6]])

#### How many dimensions?  1 = List; 2 = Table; 3 = Spatial coordinates

In [16]:
print(arr.ndim) 
# An integer: 2

2


#### What is the size of each dimension

In [17]:
print(arr.shape)
# A tuple: (2, 3), meaning 2 rows 3 cols

(2, 3)


### Array Arithmetic

#### Two NumPy Arrays

In [18]:
# Same size array
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])
print(a + b)   # [ 3  7 11]
print(a - b)   # [-1 -1 -1]


[ 3  7 11]
[-1 -1 -1]


#### NumPy Array and single number

In [19]:
#Differnt size array
a = np.array([1, 3, 5])
b = 2
print(a + b)   # [3 5 7]
print(a - b)   # [-1  1  3]


[3 5 7]
[-1  1  3]


## Array Indexing & Slicing
### Same as LISTS for 1D arrays

In [20]:
a = np.array([5, 3, 1])
print(a[0])   # 5
print(a[1:])  # [3 1]
print(a[:])   # [5 3 1]

a[1] = 4
print(a)      # [5 4 1]


5
[3 1]
[5 3 1]
[5 4 1]


### For 2+ D arrays:
numpyArray[start_row_index:end_row_index, start_column_index:end_column_index]

#### Create NumPy Array

In [21]:
b = np.array([
              [ 5,  3,  1,  5],
              [ 2,  4,  6,  7],
              [ 6,  7,  8,  6],
              [10, 20, 30, 40],    
             ])

#### Get the first row all columns

In [22]:
print(b[0,:])   # [5 3 1 5]

[5 3 1 5]


####  Get all rows and second column

In [23]:
print(b[:, 1])   # [3 4 7 20]

[ 3  4  7 20]


#### Get the element at Row 1, Col 2

In [24]:
print(b[0, 1])   # 3

3


#### Get Rows 1 through 2 and column 1 through 2

In [25]:
print(b[0:2,0:2])

[[5 3]
 [2 4]]


#### Get Rows 2 through 3 and column 1 through 3

In [26]:
print(b[1:3,0:3])

[[2 4 6]
 [6 7 8]]


### Updating NumPy Arrays

In [27]:
b = np.array([[5, 3, 1],
              [2, 4, 6]])
print(b)

[[5 3 1]
 [2 4 6]]


In [28]:
# Change a row
b[0, :] = np.array([1, 3, 5])
print(b)

[[1 3 5]
 [2 4 6]]


In [29]:
# Change a column
b[:, 1] = np.array([-3, -4])
print(b)

[[ 1 -3  5]
 [ 2 -4  6]]


In [30]:
# Change an element
b[1, 2] = 0
print(b)

[[ 1 -3  5]
 [ 2 -4  0]]


### Array Reshape
#### # Create array with 9 numbers

In [9]:
#Forward count
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [10]:
#Backward count
a = np.arange(9,0,-1)
print(a)

[9 8 7 6 5 4 3 2 1]


In [14]:
#Make the array 3 x 3
b = a.reshape(3, 3)
print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


## NumPy and Stats
### Random Numbers
#### Random integers ==> np.random.randint(low, high, size)

In [34]:
#Example:
# 1-Dim Array
samples = np.random.randint(0, 10, 10)
print(samples)

[2 4 6 6 5 2 6 3 1 4]


In [35]:
# 2 Dim Array
samples = np.random.randint(0, 10, (5, 5))
print(samples)

[[3 2 3 7 1]
 [7 6 9 1 3]
 [4 0 5 1 2]
 [5 1 3 4 1]
 [7 5 6 8 4]]


#### Normal Distribution  ==> np.random.normal(mean, std, size)

In [36]:
#Example:
# 1-Dim Array
samples = np.random.normal(10, 5, 3)
print(samples)

[7.6349884  8.03397998 7.57906486]


In [37]:
# 2 Dim Array
samples = np.random.normal(0, 1, (2, 2))
print(samples)

[[ 1.55020131 -0.00602729]
 [-0.44752714 -0.8373888 ]]


### Statistical Methods
#### Two ways to call the functions:

In [38]:
# Example:
a = np.random.randint(0, 10, 10)
print("Array:")
print(a)
print()

for i in range(len(a)):
    print("#" + str(i), " = ", a[i])

Array:
[0 9 3 1 6 7 9 4 4 8]

#0  =  0
#1  =  9
#2  =  3
#3  =  1
#4  =  6
#5  =  7
#6  =  9
#7  =  4
#8  =  4
#9  =  8


#### OPTION 1 - np.functionName(numpyArray)

In [39]:
b = np.mean(a)
print("Average:",b)

Average: 5.1


#### OPTION 2 - numpyArray.method()

In [40]:
c = a.mean()
print("Average:",c)

Average: 5.1


In [41]:
print("Sum:",np.sum(a))
print("Average:",np.mean(a))
print("Std:",np.std(a))
print("Var:",np.var(a))
print("Min:",np.min(a))
print("Max:",np.max(a))
print("Minimum number's position:",np.argmin(a)) #Return the location of the smallest Number
print("Maximum number's position:",np.argmax(a)) #Return the location of the largest Number

# or ...

Sum: 51
Average: 5.1
Std: 3.047950130825634
Var: 9.29
Min: 0
Max: 9
Minimum number's position: 0
Maximum number's position: 1


In [42]:
print("Sum:",a.sum())
print("Average:",a.mean())
print("Std:",a.std())
print("Var:",a.var())
print("Min:",a.min())
print("Max:",a.max())
print("Minimum number's position:",a.argmin())
print("Maximum number's position:",a.argmax())

Sum: 51
Average: 5.1
Std: 3.047950130825634
Var: 9.29
Min: 0
Max: 9
Minimum number's position: 0
Maximum number's position: 1


# Structured Array (Named Columns)

#### Create a list with 3 rows and 3 columns
<pre>
Column 1 = Name
Column 2 = Height in meters
Column 3 = Age
</pre>

In [49]:
#LIST
values = [
            ('Arthur',   1.8,  41), 
            ('Lancelot', 1.9,  38), 
            ('Galahad',  1.7,  38)
        ]
print(values)

[('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]


#### Create a list that matches the data list columns and corresponding datatypes

In [50]:
#Column Names and Data Types
dtype = [
            ('name', 'S10'), #S = string
            ('height', float), 
            ('age', int)
        ]

#### Create NumPy array with column names and datatypes

In [57]:
arrayWithColumns = np.array(values, dtype=dtype)
print(arrayWithColumns)
#arrayWithColumns

[(b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38) (b'Galahad', 1.7, 38)]


### Now it's easy to do Sorting, Statistics, ...
#### Sort by one column

In [60]:
#Not saved!!!
np.sort(arrayWithColumns, order='height')
print(arrayWithColumns)
print()

#SAVED!!!
arrayWithColumns = np.sort(arrayWithColumns, order='height')
print(arrayWithColumns)

[(b'Galahad', 1.7, 38) (b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38)]

[(b'Galahad', 1.7, 38) (b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38)]


### Maybe there is a tie between rows with height.  Let's add a secondary sort to break the tie

In [61]:
arrayWithColumns = np.sort(arrayWithColumns, order=['age', 'height'])
print(arrayWithColumns)

[(b'Galahad', 1.7, 38) (b'Lancelot', 1.9, 38) (b'Arthur', 1.8, 41)]


# Reading a file into NumPy Array

In [62]:
from numpy import genfromtxt

### Use first row as column titles

In [86]:
my_data = np.genfromtxt('ToyotaDataPC.csv',  #FILE NAME
                        skip_header=False,    #Do not skip first row. Contains column titles
                        encoding=None,       #Usually "None"
                        delimiter = ',',     #Comma separated value file
                        dtype=None,          #None means let Python decide on the datatypes
                        names = True         #True means use the column titles in the first row.
                       )

print(my_data.dtype)

[('ID', '<i4'), ('Model', '<U75'), ('Actual_Price', '<i4'), ('Age_08_04', '<i4'), ('KM', '<i4'), ('Fuel_Type', '<U6'), ('HP', '<i4'), ('Automatic', '<i4'), ('Weight', '<i4'), ('Automatic_airco', '<i4')]


### Skip first row (column titles) and make your own column titles.

In [87]:
my_data = np.genfromtxt('ToyotaDataPC.csv',  #FILE NAME
                        skip_header=True,    #SKIP FIRST ROW? (make your own column titles)
                        encoding=None,       #Usually "None"
                        delimiter = ',',     #Comma separated value file
                        dtype=None,          #None means let Python decide on the datatypes
                        names=['ID',         #Skipped header. Make your own column titles
                               'Model', 
                               'Price', 
                               'Age', 
                               'KM', 
                               'Fuel_Type', 
                               'HP', 
                               'Automatic', 
                               'Weight', 
                               'Automatic_airco']
                       )

#Note: dtype = None means that we will let Numpy determine the "best" datatype for each column

In [88]:
print(my_data.dtype)

[('ID', '<i4'), ('Model', '<U75'), ('Price', '<i4'), ('Age', '<i4'), ('KM', '<i4'), ('Fuel_Type', '<U6'), ('HP', '<i4'), ('Automatic', '<i4'), ('Weight', '<i4'), ('Automatic_airco', '<i4')]


In [89]:
### Print the average of the Price column (column 3)

In [97]:
print(my_data['Price'].mean())
print(np.mean(my_data['Price']))

10730.824512534818
10730.824512534818
